// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  ProcDefinition = 2,
  ProcName = 3,
  ProcBody = 4,
  BracedString = 5,
  Variable = 6,
  CommandSub = 7,
  SetExpression = 8,
  VarName = 9,
  SetValue = 10,
  QuotedString = 11,
  KeywordCommand = 12,
  TclKeyword = 13,
  ProcInvocation = 14,
  ProcInvocationName = 15,
  LineComment = 16
