// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Script = 1,
  ProcDefinition = 2,
  ProcName = 3,
  ProcBody = 4,
  BracedString = 5,
  Variable = 6,
  CommandSub = 7,
  ProcInvocation = 8,
  ProcInvocationName = 9,
  LineComment = 10
