// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hQQOPOOO]OPO'#C^OOOO'#Ce'#CeOOOO'#Cd'#CdOOOO'#Cj'#CjOOOO'#Cg'#CgQQOPOOOOOO'#C_'#C_ObOPO,58xOOOO-E6e-E6eOgOPO1G.dOlOPO7+$OOqOQO'#CaOOOO'#C`'#C`OOOO<<Gj<<GjO!SOPO'#CbO!XOPO'#CcOOOO'#Co'#CoOOOO'#Ch'#ChO!gOQO,58{OOOO,58{,58{OOOO,58|,58|OOOO,58},58}O!xOPO,58}OOOO-E6f-E6fOOOO1G.g1G.gOOOO1G.i1G.i",
  stateData: "#Z~OYSO_PO`QO~O`VO~OaYO~ObZO~Oa[O~Oa[ObdOdaOe_Of`O~O`eO~OYSO_PO`QOgfO~Oa[ObiOdaOe_Of`O~OYSO_PO`QOgjO~O_`~",
  goto: "!jdPPeknqttexP!O!YP!`PPPP!fXSOU`gRWPR^ZQ]ZTa[cXROU`gQUOSXUgRg`Qc[RhcXTOU`gTb[c",
  nodeNames: "⚠ Script ProcDefinition ProcName ProcBody BracedString Variable CommandSub ProcInvocation ProcInvocationName LineComment",
  maxTerm: 23,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ".f~RkOY!vZ]!v^s!vst#ntu%`u}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e!}#O&t#O#P!v#P#Q&y#Q#R!v#R#S%e#S#T!v#T#d%e#d#e'm#e#o%e#o#p.[#p#q!v#q#r.a#r;'S!v;'S;=`#h<%lO!vQ!{XdQOY!vZ]!v^t!vu!}!v#O#o!v#p#q!v#r;'S!v;'S;=`#h<%lO!vQ#kP;=`<%l!vR#u]YPdQOY#nZ]#n^t#ntu$nu!}#n!}#O$n#O#o#n#o#p$n#p#q#n#q#r$n#r;'S#n;'S;=`%Y<%lO#nP$sTYPOY$nZ]$n^;'S$n;'S;=`%S<%lO$nP%VP;=`<%l$nR%]P;=`<%l#n~%eOe~R%lbdQ`POY!vZ]!v^t!vu}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e#O#R!v#R#S%e#S#T!v#T#o%e#p#q!v#r;'S!v;'S;=`#h<%lO!v~&yOf~R'QXgPdQOY!vZ]!v^t!vu!}!v#O#o!v#p#q!v#r;'S!v;'S;=`#h<%lO!vR'tddQ`POY!vZ]!v^t!vu}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e#O#R!v#R#S%e#S#T!v#T#f%e#f#g)S#g#o%e#p#q!v#r;'S!v;'S;=`#h<%lO!vR)ZddQ`POY!vZ]!v^t!vu}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e#O#R!v#R#S%e#S#T!v#T#c%e#c#d*i#d#o%e#p#q!v#r;'S!v;'S;=`#h<%lO!vR*pddQ`POY!vZ]!v^t!vu}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e#O#R!v#R#S%e#S#T!v#T#V%e#V#W,O#W#o%e#p#q!v#r;'S!v;'S;=`#h<%lO!vR,VedQ`POX!vXY-hZ]!v^p!vpq-hqt!vu}!v}!O%e!O!P%e!P!Q!v!Q![%e![!c!v!c!}%e#O#R!v#R#S%e#S#T!v#T#o%e#p#q!v#r;'S!v;'S;=`#h<%lO!vR-oXdQ_POY!vZ]!v^t!vu!}!v#O#o!v#p#q!v#r;'S!v;'S;=`#h<%lO!v~.aOa~~.fOb~",
  tokenizers: [0, 1],
  topRules: {"Script":[0,1]},
  tokenPrec: 100
})
